### ISSUE TITLE
SNOPT Derivative option 0

### ISSUE THREAD

**Issue by barbara-dc** [ethz-adrl/ifopt#57]
How can I use ifopt to interface with snopt without assigning values to the Jacobian?

I found in `ifopt/ifopt_ipopt/src/snopt_solver.cc`:
`snopt.setIntParameter( "Derivative option", 1)`
which I can replace by `snopt.setIntParameter( "Derivative option",  0)`. 

However, if I leave the `FillJacobianBlock` function of the constraint class empty (as I can do when I set "jacobian_approximation" to "finite-difference-values" with ipopt), I get `WARNING`s saying that the Jacobian is empty and no solution is found.
What should I do to solve this?

**Comment by awinkler** [comment]
Thanks for mentioning this. Unfortunately this is not implemented for the SNOPT version. (only in the `ipopt_adapter` as you mentioned).  

However, SNOPT mentions (https://ccom.ucsd.edu/~optimizers/static/pdfs/snopt7-7.pdf):

> Ideally, the first derivatives (gradients) of Fi should be known and coded by the user. If
only some gradients are known, snOptA estimates the missing ones by finite differences.

But you still have to supply the sparsity pattern of the Jacobian, or conservatively estimate every element as non-zero. That's why I assume you're getting the `WARNING`, probably due to this line which will falsely specify that you have _no_ non-zero elements in your Jacobian:
https://github.com/ethz-adrl/ifopt/blob/8976a52669bd2a269254ef86ddc1e522a93fccac/ifopt_snopt/src/snopt_adapter.cc#L112

But as I said, it's not implemented for SNOPT. For IPOPT you could find it in this class:
https://github.com/ethz-adrl/ifopt/blob/8976a52669bd2a269254ef86ddc1e522a93fccac/ifopt_ipopt/src/ipopt_adapter.cc#L117
